export default [{
  heading: 'footer.getStarted',
  links: [{
    label: 'footer.wallet',
    href: 'https://www.skycoin.net/downloads',
  }, {
    label: 'footer.infographics',
    href: 'https://www.skycoin.net/infographics',
  }, {
    label: 'footer.team',
    href: 'https://www.skycoin.net/blog/statement/skycoin-team/',
  }, {
    label: 'footer.subscribe',
    href: 'https://www.skycoin.net/mailing-list',
  }, {
    label: 'footer.market',
    href: 'https://www.skycoin.net/markets',
  }, {
    label: 'footer.bitcoinTalks',
    href: 'https://bitcointalk.org/index.php?topic=380441',
  }],
}, {
  heading: 'footer.explore',
  links: [{
    label: 'footer.blog',
    href: 'https://www.skycoin.net/blog',
  }, {
    label: 'footer.whitepapers',
    href: 'https://www.skycoin.net/whitepapers',
  }, {
    label: 'footer.blockchain',
    href: 'https://explorer.skycoin.net/blocks',
  }, {
    label: 'footer.roadmap',
    href: 'https://www.skycoin.net/roadmap',
  }, {
    label: 'footer.skyMessenger',
    href: 'http://messenger.skycoin.net/',
  }, {
    label: 'footer.cxPlayground',
    href: 'http://cx.skycoin.net/',
  }],
}, {
  heading: 'footer.community',
  links: [{
    label: 'footer.reddit',
    href: 'https://www.reddit.com/r/SkycoinProject',
  }, {
    label: 'footer.twitter',
    href: 'https://twitter.com/skycoinproject',
  }, {
    label: 'footer.github',
    href: 'https://github.com/skycoin/skycoin',
  }, {
    label: 'footer.telegram',
    href: 'https://t.me/Skycoin',
  }, {
    label: 'footer.slack',
    href: 'http://skycoin.herokuapp.com/',
  }, {
    label: 'footer.discord',
    href: 'https://discord.gg/EgBenrW',
  }, {
    label: 'footer.facebook',
    href: 'https://www.facebook.com/skycoinproject',
  }, {
    label: 'footer.instagram',
    href: 'https://www.instagram.com/skycoinproject/',
  }],
}];
