language: go

go:
  - 1.9

install: true

notifications:
  email: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
#  - go get github.com/golang/lint/golint 
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -l $GO_FILES)
  - go test -cover -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 10 $GO_FILES
#  - golint -set_exit_status $(go list ./...)